<?php

namespace App\Providers;

use App\Models\Activity;
use App\Models\ClsfDefn;
use App\Models\ClsfValue;
use App\Models\Comment;
use App\Models\Feature;
use App\Models\GRN;
use App\Models\ImportLogger;
use App\Models\InternalSupplier;
use App\Models\Inventory;
use App\Models\Module;
use App\Models\NewsFeed;
use App\Models\Permission;
use App\Models\PriceDatum;
use App\Models\Product;
use App\Models\ProductClassification;
use App\Models\ProductComment;
use App\Models\ProductFeature;
use App\Models\PurchaseOrder;
use App\Models\Relationship;
use App\Models\Role;
use App\Models\RolePermission;
use App\Models\SearchHistory;
use App\Models\Setting;
use App\Models\Source;
use App\Models\Supplier;
use App\Models\Tag;
use App\Models\Task;
use App\Models\Tier;
use App\Models\UsageDatum;
use App\Models\User;
use App\Models\UserActivity;
use App\Models\UserRole;
use App\Observers\ActivityObserver;
use App\Observers\ClsfDefnObserver;
use App\Observers\ClsfValueObserver;
use App\Observers\CommentObserver;
use App\Observers\FeatureObserver;
use App\Observers\GRNObserver;
use App\Observers\ImportLoggerObserver;
use App\Observers\InternalSupplierObserver;
use App\Observers\InventoryObserver;
use App\Observers\ModuleObserver;
use App\Observers\NewsFeedObserver;
use App\Observers\PermissionObserver;
use App\Observers\PriceDatumObserver;
use App\Observers\ProductClassificationObserver;
use App\Observers\ProductCommentObserver;
use App\Observers\ProductFeatureObserver;
use App\Observers\ProductObserver;
use App\Observers\PurchaseOrderObserver;
use App\Observers\RelationshipObserver;
use App\Observers\RoleObserver;
use App\Observers\RolePermissionObserver;
use App\Observers\SearchHistoryObserver;
use App\Observers\SettingObserver;
use App\Observers\SourceObserver;
use App\Observers\SupplierObserver;
use App\Observers\TagObserver;
use App\Observers\TaskObserver;
use App\Observers\TierObserver;
use App\Observers\UsageDatumObserver;
use App\Observers\UserActivityObserver;
use App\Observers\UserObserver;
use App\Observers\UserRoleObserver;
use Illuminate\Support\ServiceProvider;

/**
 * This file was generated by laravel-kickstart. Changes may be overridden
 */
class ObserverProvider extends ServiceProvider
{
    public function boot()
    {
        GRN::observe(GRNObserver::class);
        Activity::observe(ActivityObserver::class);
        ClsfDefn::observe(ClsfDefnObserver::class);
        ClsfValue::observe(ClsfValueObserver::class);
        Comment::observe(CommentObserver::class);
        Feature::observe(FeatureObserver::class);
        ImportLogger::observe(ImportLoggerObserver::class);
        InternalSupplier::observe(InternalSupplierObserver::class);
        Inventory::observe(InventoryObserver::class);
        Module::observe(ModuleObserver::class);
        NewsFeed::observe(NewsFeedObserver::class);
        Permission::observe(PermissionObserver::class);
        PriceDatum::observe(PriceDatumObserver::class);
        Product::observe(ProductObserver::class);
        ProductClassification::observe(ProductClassificationObserver::class);
        ProductComment::observe(ProductCommentObserver::class);
        ProductFeature::observe(ProductFeatureObserver::class);
        PurchaseOrder::observe(PurchaseOrderObserver::class);
        Relationship::observe(RelationshipObserver::class);
        RolePermission::observe(RolePermissionObserver::class);
        Role::observe(RoleObserver::class);
        SearchHistory::observe(SearchHistoryObserver::class);
        Setting::observe(SettingObserver::class);
        Source::observe(SourceObserver::class);
        Supplier::observe(SupplierObserver::class);
        Tag::observe(TagObserver::class);
        Task::observe(TaskObserver::class);
        Tier::observe(TierObserver::class);
        UsageDatum::observe(UsageDatumObserver::class);
        UserActivity::observe(UserActivityObserver::class);
        UserRole::observe(UserRoleObserver::class);
        User::observe(UserObserver::class);
    }
}
