# Generated by Django 4.2.9 on 2024-03-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotByChannelView',
            fields=[
                ('Product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Dine_In', models.DecimalField(db_column='Dine In', decimal_places=2, max_digits=10)),
                ('UberEats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Deliveroo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JustEat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('City', models.CharField(max_length=255)),
                ('Period', models.DateField()),
                ('FormattedDate', models.CharField(max_length=255)),
                ('Segments', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('ProteinType', models.CharField(max_length=255)),
                ('DeliverySum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NonNullCounter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_Average', models.DecimalField(db_column='Delivery Average', decimal_places=2, max_digits=10)),
                ('DineIn_Delivery', models.DecimalField(db_column='DineIn/Delivery', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SnapshotByChannelView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotByRegionView',
            fields=[
                ('Product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Birmingham', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Belfast', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Cardiff', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Glasgow', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Liverpool', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Leeds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Manchester', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('London', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Bristol', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Period', models.DateField()),
                ('FormattedDate', models.CharField(max_length=255)),
                ('Segments', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('ProteinType', models.CharField(max_length=255)),
                ('ChannelName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SnapshotByRegionView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnapshotByVariation',
            fields=[
                ('Product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('MinPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('MaxPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('AvgPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ModePrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Period', models.DateField()),
                ('FormattedDate', models.CharField(max_length=255)),
                ('Segments', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('ProteinType', models.CharField(max_length=255)),
                ('ChannelName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SnapshotByVariation',
                'managed': False,
            },
        ),
    ]
