<?php

namespace App\Providers;

use App\Models\Activity;
use App\Models\ClsfDefn;
use App\Models\ClsfValue;
use App\Models\Comment;
use App\Models\Feature;
use App\Models\GRN;
use App\Models\ImportLogger;
use App\Models\InternalSupplier;
use App\Models\Inventory;
use App\Models\Module;
use App\Models\NewsFeed;
use App\Models\Permission;
use App\Models\PriceDatum;
use App\Models\Product;
use App\Models\ProductClassification;
use App\Models\ProductComment;
use App\Models\ProductFeature;
use App\Models\PurchaseOrder;
use App\Models\Relationship;
use App\Models\Role;
use App\Models\RolePermission;
use App\Models\SearchHistory;
use App\Models\Setting;
use App\Models\Source;
use App\Models\Supplier;
use App\Models\Tag;
use App\Models\Task;
use App\Models\Tier;
use App\Models\UsageDatum;
use App\Models\User;
use App\Models\UserActivity;
use App\Models\UserRole;
use App\Policies\ActivityPolicy;
use App\Policies\ClsfDefnPolicy;
use App\Policies\ClsfValuePolicy;
use App\Policies\CommentPolicy;
use App\Policies\FeaturePolicy;
use App\Policies\GRNPolicy;
use App\Policies\ImportLoggerPolicy;
use App\Policies\InternalSupplierPolicy;
use App\Policies\InventoryPolicy;
use App\Policies\ModulePolicy;
use App\Policies\NewsFeedPolicy;
use App\Policies\PermissionPolicy;
use App\Policies\PriceDatumPolicy;
use App\Policies\ProductClassificationPolicy;
use App\Policies\ProductCommentPolicy;
use App\Policies\ProductFeaturePolicy;
use App\Policies\ProductPolicy;
use App\Policies\PurchaseOrderPolicy;
use App\Policies\RelationshipPolicy;
use App\Policies\RolePermissionPolicy;
use App\Policies\RolePolicy;
use App\Policies\SearchHistoryPolicy;
use App\Policies\SettingPolicy;
use App\Policies\SourcePolicy;
use App\Policies\SupplierPolicy;
use App\Policies\TagPolicy;
use App\Policies\TaskPolicy;
use App\Policies\TierPolicy;
use App\Policies\UsageDatumPolicy;
use App\Policies\UserActivityPolicy;
use App\Policies\UserPolicy;
use App\Policies\UserRolePolicy;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider;

/**
 * This file was generated by laravel-kickstart. Changes may be overridden
 */
class PolicyProvider extends AuthServiceProvider
{
    protected $policies = [
        GRN::class => GRNPolicy::class,
        Activity::class => ActivityPolicy::class,
        ClsfDefn::class => ClsfDefnPolicy::class,
        ClsfValue::class => ClsfValuePolicy::class,
        Comment::class => CommentPolicy::class,
        Feature::class => FeaturePolicy::class,
        ImportLogger::class => ImportLoggerPolicy::class,
        InternalSupplier::class => InternalSupplierPolicy::class,
        Inventory::class => InventoryPolicy::class,
        Module::class => ModulePolicy::class,
        NewsFeed::class => NewsFeedPolicy::class,
        Permission::class => PermissionPolicy::class,
        PriceDatum::class => PriceDatumPolicy::class,
        Product::class => ProductPolicy::class,
        ProductClassification::class => ProductClassificationPolicy::class,
        ProductComment::class => ProductCommentPolicy::class,
        ProductFeature::class => ProductFeaturePolicy::class,
        PurchaseOrder::class => PurchaseOrderPolicy::class,
        Relationship::class => RelationshipPolicy::class,
        RolePermission::class => RolePermissionPolicy::class,
        Role::class => RolePolicy::class,
        SearchHistory::class => SearchHistoryPolicy::class,
        Setting::class => SettingPolicy::class,
        Source::class => SourcePolicy::class,
        Supplier::class => SupplierPolicy::class,
        Tag::class => TagPolicy::class,
        Task::class => TaskPolicy::class,
        Tier::class => TierPolicy::class,
        UsageDatum::class => UsageDatumPolicy::class,
        UserActivity::class => UserActivityPolicy::class,
        UserRole::class => UserRolePolicy::class,
        User::class => UserPolicy::class,
    ];


    /**
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        //
    }
}
