name: Laravel and React Deployment

on:
  push:
    branches:
      - productportal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Install Node.js dependencies
      run: |
        cd react-frontend
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install
        npm run build
      env:
        NODE_OPTIONS: --openssl-legacy-provider

    - name: Move React build to Laravel public
      run: |
        cp -r react-frontend/build/* laravel-backend/public/

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.33'

    - name: Install Composer dependencies
      run: |
        cd laravel-backend
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./laravel-backend
